<a href="https://colab.research.google.com/github/nirmit27/tensorflow-udemy/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to <b>TensorFlow</b>&nbsp;&nbsp;🤖

> When in **doubt**, **code** it out.

In [2]:
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

rng = np.random.default_rng(seed=27)

tf.__version__

'2.15.0'

### Creating **unchangeable** tensors with `tf.constant()`

In [3]:
x = tf.constant(np.random.randint(10))

y = tf.constant(rng.random((3,3)))

z = tf.constant([[
    [i for i in range(1, 4)], [i for i in range(4, 7)],
],
     [
         [i for i in range(7, 10)], [i for i in range(10, 13)]
     ],
     [
         [i for i in range(13, 16)], [i for i in range(16, 19)]
     ]
])

x, y, z

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.69773622, 0.31381427, 0.1211971 ],
        [0.32359152, 0.93121187, 0.78966731],
        [0.01001912, 0.19893322, 0.29311369]])>,
 <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>)

### Creating **changeable** tensors with `tf.Variable()`

In [4]:
a = tf.Variable([[2, 3], [4, 5]])

print(f"Before changes :\n{a}\n")

a[1, 0].assign(6)

print(f"After changes :\n{a}\n")

Before changes :
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

After changes :
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [6, 5]], dtype=int32)>



### Creating **random** tensors with `tf.random.Generator.from_seed()`

In [5]:
# Generator object for creating random tensors ...
rg1 = tf.random.Generator.from_seed(42)
rg2 = tf.random.Generator.from_seed(42)

rg3 = tf.random.Generator.from_seed(27)

# Output values from a NORMAL DISTRIBUTION ...
r1 = rg1.normal(shape=[2, 3])
r2 = rg2.normal(shape=[2, 3])

r3 = rg3.normal(shape=[2, 3])

r1 == r2, r1 == r3

(<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True]])>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False]])>)

### **Shuffling** the order
> Keep in mind the **Global** and **Operation**-level seeds.

In [6]:
sample = tf.constant([[12, 24],
                      [23, 45],
                      [34, 90]])

# for generating REPRODUCIBLE results ...
# tf.random.set_seed(21)

sample = tf.random.shuffle(sample, seed=21)

sample.numpy()

array([[12, 24],
       [23, 45],
       [34, 90]], dtype=int32)

### **Other** ways for creation

In [7]:
# making a 3-D Tensor from a 1-D Numpy Array ...
arr = np.arange(1, 25, dtype=np.int32)
tensor = tf.constant(arr, shape=(2, 3, 4))      #  2*3*4 = 24 i.e. make sure that the number of elements match!

arr, tensor, tensor.ndim

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 3)

### Fetching **information** from a tensor

In [8]:
rank_4 = tf.ones(shape=[2,3,4,5])
print(f"Shape of the tensor\t:\t{rank_4.shape}\nRank of the tensor\t:\t{rank_4.ndim}\nSize of the tensor\t:\t{tf.size(rank_4).numpy()}\nDatatype of the tensor\t:\t{rank_4.dtype}")

Shape of the tensor	:	(2, 3, 4, 5)
Rank of the tensor	:	4
Size of the tensor	:	120
Datatype of the tensor	:	<dtype: 'float32'>


### **Indexing** and **Expanding** of tensors


#### _Indexing_

In [9]:
# First 2 elements of each dimension
first_2 = tensor[:2, :2, :2]
first_except_final = tensor[:1, :1, :]
first_except_2nd_last = tensor[:1, :, :1]

# first_2
# first_except_final
first_except_2nd_last

<tf.Tensor: shape=(1, 3, 1), dtype=int32, numpy=
array([[[1],
        [5],
        [9]]], dtype=int32)>

#### _Expanding_

In [10]:
# Last item of EACH row
last = tensor[:2, :, -1]

# Adding EXTRA dimension to the Rank 3 tensor ...
tensor_ = tensor[..., tf.newaxis]

# Alternatively ... expanding the nth axis ...
tensor__ = tf.expand_dims(tensor, axis=-1)

tensor, tensor__

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4, 1), dtype=int32, numpy=
 array([[[[ 1],
          [ 2],
          [ 3],
          [ 4]],
 
         [[ 5],
          [ 6],
          [ 7],
          [ 8]],
 
         [[ 9],
          [10],
          [11],
          [12]]],
 
 
        [[[13],
          [14],
          [15],
          [16]],
 
         [[17],
          [18],
          [19],
          [20]],
 
         [[21],
          [22],
          [23],
          [24]]]], dtype=int32)>)

#### _Re-assigning values_

In [11]:
example = np.arange(1, 7, dtype=np.int32)
example = tf.constant(example, shape=(2, 3))
example = tf.expand_dims(example, axis=-1)

example_ = tf.Variable(example)
example_[:, :, 0].assign([[23, 24, 25], [26, 27, 28]])

example_.numpy()

array([[[23],
        [24],
        [25]],

       [[26],
        [27],
        [28]]], dtype=int32)

## Matrix **Multiplication**

> #### For checking compatibility of Multiplication

In [12]:
def check_order(m1, m2):
    if m1.shape[1] == m2.shape[0]:
        return True
    return False

In [13]:
result_ = tf.constant([])

m1 =  tf.constant([[1, 2, 1],
                [0, 1, 0],
                [2, 3, 4]])

m2 = tf.constant([[2, 5],
                  [6, 7],
                  [1, 8]])

m2 = tf.reshape(m2, shape=(2, 3))
m2 = tf.transpose(m2)

if check_order(m1, m2):
    result_ = tf.matmul(m1, m2)
    print(m1.numpy(), "\n\n", m2.numpy(), "\n\n", result_.numpy())
else:
    print("Incompatible shapes!")

[[1 2 1]
 [0 1 0]
 [2 3 4]] 

 [[2 7]
 [5 1]
 [6 8]] 

 [[18 17]
 [ 5  1]
 [43 49]]


### **Dot** Product

> #### `axes` probably corresponds to the **degree of correlation**

In [14]:
m_1 = tf.constant([[1, 2], [4, 5]])

m_2 = tf.constant([[7, 8, 12, 15], [9, 10, 13, 16]])

ax_0 = tf.tensordot(m_1, m_2, axes=0)
ax_1 = tf.tensordot(m_1, m_2, axes=1)

ax_0, ax_1

(<tf.Tensor: shape=(2, 2, 2, 4), dtype=int32, numpy=
 array([[[[ 7,  8, 12, 15],
          [ 9, 10, 13, 16]],
 
         [[14, 16, 24, 30],
          [18, 20, 26, 32]]],
 
 
        [[[28, 32, 48, 60],
          [36, 40, 52, 64]],
 
         [[35, 40, 60, 75],
          [45, 50, 65, 80]]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 25,  28,  38,  47],
        [ 73,  82, 113, 140]], dtype=int32)>)

### Changing **Datatypes**

In [15]:
tf1 = tf.cast(tf.constant([10, 20]), dtype=tf.float32)
tf2 = tf.cast(tf.constant([10.7, 90.823]), dtype=tf.int32)

tf1.numpy(), tf2.numpy()

(array([10., 20.], dtype=float32), array([10, 90], dtype=int32))

## **Aggregation** Operations
 - #### Minimum

In [16]:
ex1 = tf.constant(np.random.randint(1, 100, size=10))
print(f"At index {tf.argmin(ex1).numpy()}, the value is {ex1.numpy()[tf.argmin(ex1).numpy()]}.")
print(f"Minimum value in {ex1.numpy()} = {tf.reduce_min(ex1).numpy()}")

At index 2, the value is 8.
Minimum value in [67 63  8 31 16 74 88 43 72 49] = 8


- #### Maximum

In [17]:
print(f"At index {tf.argmax(ex1).numpy()}, the value is {ex1.numpy()[tf.argmax(ex1).numpy()]}.")
print(f"Maximum value in {ex1.numpy()} = {tf.reduce_max(ex1).numpy()}")

At index 6, the value is 88.
Maximum value in [67 63  8 31 16 74 88 43 72 49] = 88


- #### Mean

In [18]:
print(f"Mean value in {ex1.numpy()} = {tf.reduce_mean(ex1).numpy()}")

Mean value in [67 63  8 31 16 74 88 43 72 49] = 51


- #### Sum

In [19]:
print(f"Sum of values in {ex1.numpy()} = {tf.reduce_sum(ex1).numpy()}")

Sum of values in [67 63  8 31 16 74 88 43 72 49] = 511


- #### **Standard Deviation** and **Variance**
You'll need to **typecast** the vector values to **float** dtype using the `tf.math.reduce_std()` and `tf.math.reduce_variance()` functions.

In [20]:
std = tf.math.reduce_std(tf.cast(ex1, dtype=tf.float32)).numpy()
var = tf.math.reduce_variance(tf.cast(ex1, dtype=tf.float32)).numpy()

print(f"Standard Deviation = {std:.2f} and Variance = {var:.2f}, such that ({std:.2f})^2 = {var:.2f} is {std**2 == var}.")

Standard Deviation = 25.06 and Variance = 628.09, such that (25.06)^2 = 628.09 is False.


Tensorflow **Probability** is needed for calculating **variance**.

In [21]:
print(f"Variance = {tfp.stats.variance(ex1).numpy()}")

Variance = 628


- ### Finding **positional** _minimum_ and _maximum_ values in a tensor
> ##### `axis = 1` implies along the ROWS
> ##### `axis = 0` implies along the COLS


In [22]:
F = rg3.uniform(shape=[10, 5])

print(F.numpy(),end='\n\n')

for i in range(F.shape[0]):
    print(f"Row #{i+1}\t-\tMaximum value : {F.numpy()[i][tf.argmax(F, axis=1).numpy()[i]]}\tMinimum value : {F.numpy()[i][tf.argmin(F, axis=1).numpy()[i]]}")

print(end='\n')

for j in range(F.shape[1]):
    print(f"Column #{j+1}\t-\tMaximum value : {F.numpy()[tf.argmax(F, axis=0).numpy()[j]][j]}\tMinimum value : {F.numpy()[tf.argmin(F, axis=0).numpy()[j]][j]}")


[[0.42663002 0.95090914 0.7754806  0.7937598  0.50849986]
 [0.9404652  0.78537667 0.06498516 0.6868875  0.7994733 ]
 [0.13043523 0.55487096 0.7927698  0.34447002 0.37951756]
 [0.7478161  0.12829113 0.17944527 0.40939128 0.17074227]
 [0.08954501 0.6504321  0.4854176  0.538273   0.02675951]
 [0.5285536  0.42530107 0.67171764 0.64924705 0.13024127]
 [0.40005922 0.30875564 0.8012408  0.6852087  0.03802454]
 [0.78770757 0.10308468 0.9330081  0.783924   0.15490389]
 [0.4903667  0.97904086 0.6646495  0.99244666 0.05077875]
 [0.6777401  0.2942425  0.41049325 0.49719965 0.99132764]]

Row #1	-	Maximum value : 0.9509091377258301	Minimum value : 0.42663002014160156
Row #2	-	Maximum value : 0.9404652118682861	Minimum value : 0.06498515605926514
Row #3	-	Maximum value : 0.7927697896957397	Minimum value : 0.13043522834777832
Row #4	-	Maximum value : 0.7478160858154297	Minimum value : 0.12829113006591797
Row #5	-	Maximum value : 0.6504321098327637	Minimum value : 0.02675950527191162
Row #6	-	Maximum v

## **Squeezing** Tensors
> #### Removing all the 1-dimensional axes

In [23]:
tf.random.set_seed(27)                                                      # for the reproducible results
S = tf.constant(tf.random.uniform(shape=[2, 2]), shape=(1,1,1,1,2,2))       # adding 1-dimensional axes using shape attribute
S_squeezed = tf.squeeze(S)                                                  # removing 1-dimensional axes from the tensor

print(f"Before squeeze operation : {S.shape}\nAfter squeeze operation  : {S_squeezed.shape}")

Before squeeze operation : (1, 1, 1, 1, 2, 2)
After squeeze operation  : (2, 2)


## **One-Hot** Encoding

#### For example, consider the following matrix ...

| Red   | Green | Blue |
| ----- | ----- | ---- |
| 0     | 0     | 1    |
| 0     | 1     | 0    |
| 1     | 0     | 0    |

<br>

> Red corresponds to <0, 0, 1><br>
> Green corresponds to <0, 1, 0><br>
> Blue corresponds to <1, 0, 0><br>

In [24]:
indices = [0, 1, 2, 3]
O = tf.one_hot(indices, depth=4)

O.numpy()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

### Adding **custom** __on/off__ values

In [25]:
custom_O = tf.one_hot(indices, on_value="Yes", off_value="No", depth=3, dtype=tf.string)
custom_O.numpy()

array([[b'Yes', b'No', b'No'],
       [b'No', b'Yes', b'No'],
       [b'No', b'No', b'Yes'],
       [b'No', b'No', b'No']], dtype=object)

## Other **math operations**
- Squaring
- Square Root, which needs the typecasting of the tensor to `tf.float32`
- Log

In [26]:
Q = tf.range(1, 10)         # Sample tensor

sqr = tf.square(Q).numpy()
sqrt = tf.math.sqrt(tf.cast(Q, dtype=tf.float32)).numpy()
log = tf.math.log(tf.cast(Q, dtype=tf.float32)).numpy()

print(f"Given tensor\t:\t{Q}\nSquared tensor\t:\t{sqr}\n\nSquare Root tensor\t:\t{sqrt}\n\nNatural log tensor\t:\t{log}\n\n")

Given tensor	:	[1 2 3 4 5 6 7 8 9]
Squared tensor	:	[ 1  4  9 16 25 36 49 64 81]

Square Root tensor	:	[1.        1.4142135 1.7320508 2.        2.2360678 2.4494896 2.6457512
 2.828427  3.       ]

Natural log tensor	:	[0.        0.6931472 1.0986123 1.3862944 1.609438  1.7917595 1.9459102
 2.0794415 2.1972246]




## **Concatenation** operation

In [27]:
Q = tf.reshape(Q, shape=(3,3))

concat_along_rows = tf.concat([Q, Q], axis=1)
concat_along_cols = tf.concat([Q, Q], axis=0)

print(f"Concatentation along the COLUMNS :\n\n{concat_along_cols.numpy()}\n\nConcatentation along the ROWS :\n\n{concat_along_rows.numpy()}")

Concatentation along the COLUMNS :

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]

Concatentation along the ROWS :

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


## Operations on **GPU**
> When ran on Linux Cloud env. of GitHub Codespaces, **GPU was NOT available**!

### For accessing the **GPU Runtime**
1. Go to `Runtime` option of the **header** in **Google Colab**.
2. Select the `Change runtime type` option of the **dropdown menu**.
3. Select the `T4 GPU` option as the **Hardware Accelearator**.
4. The `Runtime` will be **disconnected** and **deleted**.
5. `CTRL + F9` to **re-run** all the cells.


In [30]:
#@title Checking if **GPU** is available or not

print("Available") if tf.test.is_gpu_available('GPU') else print("Not available")

Available


In [29]:
#@title Enlisting the **physical devices** available for use.

for device in tf.config.list_physical_devices():
  print(device[0])

/physical_device:CPU:0
/physical_device:GPU:0


In [32]:
#@title Specifications of the **GPU** under use by the runtime.

!nvidia-smi

Sat Feb 17 03:58:15 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P0              30W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--