<a href="https://colab.research.google.com/github/nirmit27/tensorflow-udemy/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to <b>TensorFlow</b>&nbsp;&nbsp;🤖

> When in **doubt**, **code** it out.

In [63]:
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

rng = np.random.default_rng(seed=27)

tf.__version__

'2.15.0'

### Creating **unchangeable** tensors with `tf.constant()`

In [3]:
x = tf.constant(np.random.randint(10))

y = tf.constant(rng.random((3,3)))

z = tf.constant([[
    [i for i in range(1, 4)], [i for i in range(4, 7)],
],
     [
         [i for i in range(7, 10)], [i for i in range(10, 13)]
     ],
     [
         [i for i in range(13, 16)], [i for i in range(16, 19)]
     ]
])

x, y, z

(<tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.69773622, 0.31381427, 0.1211971 ],
        [0.32359152, 0.93121187, 0.78966731],
        [0.01001912, 0.19893322, 0.29311369]])>,
 <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>)

### Creating **changeable** tensors with `tf.Variable()`

In [4]:
a = tf.Variable([[2, 3], [4, 5]])

print(f"Before changes :\n{a}\n")

a[1, 0].assign(6)

print(f"After changes :\n{a}\n")

Before changes :
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

After changes :
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [6, 5]], dtype=int32)>



### Creating **random** tensors with `tf.random.Generator.from_seed()`

In [5]:
# Generator object for creating random tensors ...
rg1 = tf.random.Generator.from_seed(42)
rg2 = tf.random.Generator.from_seed(42)

rg3 = tf.random.Generator.from_seed(27)

# Output values from a NORMAL DISTRIBUTION ...
r1 = rg1.normal(shape=[2, 3])
r2 = rg2.normal(shape=[2, 3])

r3 = rg3.normal(shape=[2, 3])

r1 == r2, r1 == r3

(<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True]])>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False]])>)

### **Shuffling** the order
> Keep in mind the **Global** and **Operation**-level seeds.

In [6]:
sample = tf.constant([[12, 24],
                      [23, 45],
                      [34, 90]])

# for generating REPRODUCIBLE results ...
# tf.random.set_seed(21)

sample = tf.random.shuffle(sample, seed=21)

sample.numpy()

array([[12, 24],
       [23, 45],
       [34, 90]], dtype=int32)

### **Other** ways for creation

In [7]:
# making a 3-D Tensor from a 1-D Numpy Array ...
arr = np.arange(1, 25, dtype=np.int32)
tensor = tf.constant(arr, shape=(2, 3, 4))      #  2*3*4 = 24 i.e. make sure that the number of elements match!

arr, tensor, tensor.ndim

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 3)

### Fetching **information** from a tensor

In [8]:
rank_4 = tf.ones(shape=[2,3,4,5])
print(f"Shape of the tensor\t:\t{rank_4.shape}\nRank of the tensor\t:\t{rank_4.ndim}\nSize of the tensor\t:\t{tf.size(rank_4).numpy()}\nDatatype of the tensor\t:\t{rank_4.dtype}")

Shape of the tensor	:	(2, 3, 4, 5)
Rank of the tensor	:	4
Size of the tensor	:	120
Datatype of the tensor	:	<dtype: 'float32'>


### **Indexing** and **Expanding** of tensors


#### _Indexing_

In [9]:
# First 2 elements of each dimension
first_2 = tensor[:2, :2, :2]
first_except_final = tensor[:1, :1, :]
first_except_2nd_last = tensor[:1, :, :1]

# first_2
# first_except_final
first_except_2nd_last

<tf.Tensor: shape=(1, 3, 1), dtype=int32, numpy=
array([[[1],
        [5],
        [9]]], dtype=int32)>

#### _Expanding_

In [10]:
# Last item of EACH row
last = tensor[:2, :, -1]

# Adding EXTRA dimension to the Rank 3 tensor ...
tensor_ = tensor[..., tf.newaxis]

# Alternatively ... expanding the nth axis ...
tensor__ = tf.expand_dims(tensor, axis=-1)

tensor, tensor__

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4, 1), dtype=int32, numpy=
 array([[[[ 1],
          [ 2],
          [ 3],
          [ 4]],
 
         [[ 5],
          [ 6],
          [ 7],
          [ 8]],
 
         [[ 9],
          [10],
          [11],
          [12]]],
 
 
        [[[13],
          [14],
          [15],
          [16]],
 
         [[17],
          [18],
          [19],
          [20]],
 
         [[21],
          [22],
          [23],
          [24]]]], dtype=int32)>)

#### _Re-assigning values_

In [11]:
example = np.arange(1, 7, dtype=np.int32)
example = tf.constant(example, shape=(2, 3))
example = tf.expand_dims(example, axis=-1)

example_ = tf.Variable(example)
example_[:, :, 0].assign([[23, 24, 25], [26, 27, 28]])

example_.numpy()

array([[[23],
        [24],
        [25]],

       [[26],
        [27],
        [28]]], dtype=int32)

## Matrix **Multiplication**

> #### For checking compatibility of Multiplication

In [12]:
def check_order(m1, m2):
    if m1.shape[1] == m2.shape[0]:
        return True
    return False

In [13]:
result_ = tf.constant([])

m1 =  tf.constant([[1, 2, 1],
                [0, 1, 0],
                [2, 3, 4]])

m2 = tf.constant([[2, 5],
                  [6, 7],
                  [1, 8]])

m2 = tf.reshape(m2, shape=(2, 3))
m2 = tf.transpose(m2)

if check_order(m1, m2):
    result_ = tf.matmul(m1, m2)
    print(m1.numpy(), "\n\n", m2.numpy(), "\n\n", result_.numpy())
else:
    print("Incompatible shapes!")

[[1 2 1]
 [0 1 0]
 [2 3 4]] 

 [[2 7]
 [5 1]
 [6 8]] 

 [[18 17]
 [ 5  1]
 [43 49]]


### **Dot** Product

> #### `axes` probably corresponds to 

In [14]:
m_1 = tf.constant([[1, 2], [4, 5]])

m_2 = tf.constant([[7, 8, 12, 15], [9, 10, 13, 16]])

ax_0 = tf.tensordot(m_1, m_2, axes=0)
ax_1 = tf.tensordot(m_1, m_2, axes=1)

ax_0, ax_1

(<tf.Tensor: shape=(2, 2, 2, 4), dtype=int32, numpy=
 array([[[[ 7,  8, 12, 15],
          [ 9, 10, 13, 16]],
 
         [[14, 16, 24, 30],
          [18, 20, 26, 32]]],
 
 
        [[[28, 32, 48, 60],
          [36, 40, 52, 64]],
 
         [[35, 40, 60, 75],
          [45, 50, 65, 80]]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 25,  28,  38,  47],
        [ 73,  82, 113, 140]], dtype=int32)>)

### Changing **Datatypes**

In [17]:
tf1 = tf.cast(tf.constant([10, 20]), dtype=tf.float32)
tf2 = tf.cast(tf.constant([10.7, 90.823]), dtype=tf.int32)

tf1.numpy(), tf2.numpy()

(array([10., 20.], dtype=float32), array([10, 90], dtype=int32))

## **Aggregation** Operations
 - #### Minimum

In [133]:
ex1 = tf.constant(np.random.randint(1, 100, size=10))
print(f"At index {tf.argmin(ex1).numpy()}, the value is {ex1.numpy()[tf.argmin(ex1).numpy()]}.")
print(f"Minimum value in {ex1.numpy()} = {tf.reduce_min(ex1).numpy()}")

At index 2, the value is 5.
Minimum value in [32 98  5 28 47 96 73 59 78 39] = 5


- #### Maximum

In [132]:
print(f"At index {tf.argmax(ex1).numpy()}, the value is {ex1.numpy()[tf.argmax(ex1).numpy()]}.")
print(f"Maximum value in {ex1.numpy()} = {tf.reduce_max(ex1).numpy()}")

At index 2, the value is 99.
Maximum value in [41 60 99 37 94 81 79 10 69 51] = 99


- #### Mean

In [35]:
print(f"Mean value in {ex1.numpy()} = {tf.reduce_mean(ex1).numpy()}")

Mean value in [41 60 99 37 94 81 79 10 69 51] = 62


- #### Sum

In [36]:
print(f"Sum of values in {ex1.numpy()} = {tf.reduce_sum(ex1).numpy()}")

Sum of values in [41 60 99 37 94 81 79 10 69 51] = 621


- #### **Standard Deviation** and **Variance**
You'll need to **typecast** the vector values to **float** dtype using the `tf.math.reduce_std()` and `tf.math.reduce_variance()` functions.

In [61]:
std = tf.math.reduce_std(tf.cast(ex1, dtype=tf.float32)).numpy()
var = tf.math.reduce_variance(tf.cast(ex1, dtype=tf.float32)).numpy()

print(f"Standard Deviation = {std:.2f} and Variance = {var:.2f}, such that ({std:.2f})^2 = {var:.2f} is {std**2 == var}.")

Standard Deviation = 26.43 and Variance = 698.69, such that (26.43)^2 = 698.69 is False.


Tensorflow **Probability** is needed for calculating **variance**.

In [72]:
print(f"Variance = {tfp.stats.variance(ex1).numpy()}")

Variance = 698


- ### Finding **positional** _minimum_ and _maximum_ values in a tensor
> ##### `axis = 1` implies along the ROWS
> ##### `axis = 0` implies along the COLS


In [136]:
F = rg3.uniform(shape=[10, 5])

print(F.numpy(),end='\n\n')

for i in range(F.shape[0]):
    print(f"Row #{i+1}\t-\tMaximum value : {F.numpy()[i][tf.argmax(F, axis=1).numpy()[i]]}\tMinimum value : {F.numpy()[i][tf.argmin(F, axis=1).numpy()[i]]}")

print(end='\n')

for j in range(F.shape[1]):
    print(f"Column #{j+1}\t-\tMaximum value : {F.numpy()[tf.argmax(F, axis=0).numpy()[j]][j]}\tMinimum value : {F.numpy()[tf.argmin(F, axis=0).numpy()[j]][j]}")


[[0.8993373  0.88378036 0.41923654 0.21189368 0.73925066]
 [0.67720103 0.44673777 0.6203569  0.16035867 0.37029266]
 [0.01169467 0.71470606 0.69681764 0.36679387 0.6401024 ]
 [0.5637288  0.683892   0.7497109  0.15872943 0.93404984]
 [0.7439221  0.8204881  0.66244435 0.6527033  0.9074143 ]
 [0.96238065 0.0176084  0.10582292 0.51853156 0.6537857 ]
 [0.2711047  0.3220476  0.04456604 0.66971266 0.5760596 ]
 [0.9082918  0.6390605  0.9101312  0.23432922 0.20344794]
 [0.5190834  0.61612797 0.43161523 0.35779607 0.9292575 ]
 [0.71951675 0.8852018  0.26179063 0.01353407 0.2498759 ]]

Row #1	-	Maximum value : 0.8993372917175293	Minimum value : 0.21189367771148682
Row #2	-	Maximum value : 0.6772010326385498	Minimum value : 0.16035866737365723
Row #3	-	Maximum value : 0.7147060632705688	Minimum value : 0.011694669723510742
Row #4	-	Maximum value : 0.9340498447418213	Minimum value : 0.1587294340133667
Row #5	-	Maximum value : 0.9074143171310425	Minimum value : 0.6527032852172852
Row #6	-	Maximum va

## **Squeezing** Tensors
> #### Removing all the 1-dimensional axes

In [160]:
tf.random.set_seed(27)                                                      # for the reproducible results
S = tf.constant(tf.random.uniform(shape=[2, 2]), shape=(1,1,1,1,2,2))       # adding 1-dimensional axes using shape attribute
S_squeezed = tf.squeeze(S)                                                  # removing 1-dimensional axes from the tensor

print(f"Before squeeze operation : {S.shape}\nAfter squeeze operation  : {S_squeezed.shape}")

Before squeeze operation : (1, 1, 1, 1, 2, 2)
After squeeze operation  : (2, 2)
