<a href="https://colab.research.google.com/github/nirmit27/tensorflow-udemy/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

tf.__version__

In [ ]:
x = tf.constant(np.random.randint(1, 11))
y = tf.constant(np.array(
    [np.linspace(1, 4, num=3),np.linspace(4, 6, num=3)]
))

y.ndim, y

(2,
 <tf.Tensor: shape=(2, 3), dtype=float64, numpy=
 array([[1. , 2.5, 4. ],
        [4. , 5. , 6. ]])>)

In [43]:
z = tf.constant([[
    [i for i in range(1, 4)], [i for i in range(4, 7)],
],
     [
         [i for i in range(7, 10)], [i for i in range(10, 13)]
     ],
     [
         [i for i in range(13, 16)], [i for i in range(16, 19)]
     ]
])

z.ndim, z

(3,
 <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>)