<a href="https://colab.research.google.com/github/nirmit27/tensorflow-udemy/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to <b>TensorFlow</b>&nbsp;&nbsp;🤖

> When in **doubt**, **code** it out.

In [93]:
import numpy as np
import tensorflow as tf

rng = np.random.default_rng(seed=27)

tf.__version__

'2.15.0'

### Creating **unchangeable** tensors with `tf.constant()`

In [94]:
x = tf.constant(np.random.randint(10))

y = tf.constant(rng.random((3,3)))

z = tf.constant([[
    [i for i in range(1, 4)], [i for i in range(4, 7)],
],
     [
         [i for i in range(7, 10)], [i for i in range(10, 13)]
     ],
     [
         [i for i in range(13, 16)], [i for i in range(16, 19)]
     ]
])

x, y, z

(<tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.69773622, 0.31381427, 0.1211971 ],
        [0.32359152, 0.93121187, 0.78966731],
        [0.01001912, 0.19893322, 0.29311369]])>,
 <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>)

### Creating **changeable** tensors with `tf.Variable()`

In [154]:
a = tf.Variable([[2, 3], [4, 5]])

print(f"Before changes :\n{a}\n")

a[1, 0].assign(6)

print(f"After changes :\n{a}\n")

Before changes :
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

After changes :
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [6, 5]], dtype=int32)>



### Creating **random** tensors with `tf.random.Generator.from_seed()`

In [96]:
# Generator object for creating random tensors ...
rg1 = tf.random.Generator.from_seed(42)
rg2 = tf.random.Generator.from_seed(42)

rg3 = tf.random.Generator.from_seed(27)

# Output values from a NORMAL DISTRIBUTION ...
r1 = rg1.normal(shape=[2, 3])
r2 = rg2.normal(shape=[2, 3])

r3 = rg3.normal(shape=[2, 3])

r1 == r2, r1 == r3

(<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True]])>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False]])>)

### **Shuffling** the order
> Keep in mind the **Global** and **Operation**-level seeds.

In [97]:
sample = tf.constant([[12, 24],
                      [23, 45],
                      [34, 90]])

# for generating REPRODUCIBLE results ...
# tf.random.set_seed(21)

sample = tf.random.shuffle(sample, seed=21)

sample.numpy()

array([[12, 24],
       [23, 45],
       [34, 90]], dtype=int32)

### **Other** ways for creation

In [138]:
# making a 3-D Tensor from a 1-D Numpy Array ...
arr = np.arange(1, 25, dtype=np.int32)
tensor = tf.constant(arr, shape=(2, 3, 4))      #  2*3*4 = 24 i.e. make sure that the number of elements match!

arr, tensor, tensor.ndim

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 3)

### Fetching **information** from a tensor

In [121]:
rank_4 = tf.ones(shape=[2,3,4,5])
print(f"Shape of the tensor\t:\t{rank_4.shape}\nRank of the tensor\t:\t{rank_4.ndim}\nSize of the tensor\t:\t{tf.size(rank_4).numpy()}\nDatatype of the tensor\t:\t{rank_4.dtype}")

Shape of the tensor	:	(2, 3, 4, 5)
Rank of the tensor	:	4
Size of the tensor	:	120
Datatype of the tensor	:	<dtype: 'float32'>


### **Indexing** and **Expanding** of tensors


#### _Indexing_

In [139]:
# First 2 elements of each dimension
first_2 = tensor[:2, :2, :2]
first_except_final = tensor[:1, :1, :]
first_except_2nd_last = tensor[:1, :, :1]

# first_2
# first_except_final
first_except_2nd_last

<tf.Tensor: shape=(1, 3, 1), dtype=int32, numpy=
array([[[1],
        [5],
        [9]]], dtype=int32)>

#### _Expanding_

In [ ]:
# Last item of EACH row
last = tensor[:2, :, -1]

# Adding EXTRA dimension to the Rank 3 tensor ...
tensor_ = tensor[..., tf.newaxis]

# Alternatively ... expanding the nth axis ...
tensor__ = tf.expand_dims(tensor, axis=-1)

tensor, tensor__

In [170]:
example = np.arange(1, 7, dtype=np.int32)
example = tf.constant(example, shape=(2, 3))

tf.expand_dims(example, axis=-1)

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>